// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// coord_to_h3_int
uint64_t coord_to_h3_int(double lat, double lon, int res);
RcppExport SEXP _placekey_coord_to_h3_int(SEXP latSEXP, SEXP lonSEXP, SEXP resSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lat(latSEXP);
    Rcpp::traits::input_parameter< double >::type lon(lonSEXP);
    Rcpp::traits::input_parameter< int >::type res(resSEXP);
    rcpp_result_gen = Rcpp::wrap(coord_to_h3_int(lat, lon, res));
    return rcpp_result_gen;
END_RCPP
}
// h3_string_to_int
uint64_t h3_string_to_int(String index);
RcppExport SEXP _placekey_h3_string_to_int(SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(h3_string_to_int(index));
    return rcpp_result_gen;
END_RCPP
}
// h3_int_to_string
String h3_int_to_string(uint64_t index);
RcppExport SEXP _placekey_h3_int_to_string(SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< uint64_t >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(h3_int_to_string(index));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_placekey_coord_to_h3_int", (DL_FUNC) &_placekey_coord_to_h3_int, 3},
    {"_placekey_h3_string_to_int", (DL_FUNC) &_placekey_h3_string_to_int, 1},
    {"_placekey_h3_int_to_string", (DL_FUNC) &_placekey_h3_int_to_string, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_placekey(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
