# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Return the raw 64 bit inter H3 index from a latitude, longitude and resolution
#' @param lat latitude in degrees
#' @param lon longitude in degrees
#' @param resolution resolution, higher is more granular
#' @export
coord_to_h3_int <- function(lat, lon, res) {
    .Call('_placekey_coord_to_h3_int', PACKAGE = 'placekey', lat, lon, res)
}

#' Convert an H3 index string to 64 bit integer
#'
#' h3_string_to_int takes an h3 index represented as a hexadecimal string and returns the integer format.
#'
#' @param index h3 index as a hex representation character vector. See \code{\link{getIndexFromCoords}}
#' @export
h3_string_to_int <- function(index) {
    .Call('_placekey_h3_string_to_int', PACKAGE = 'placekey', index)
}

#' Returns string format of an H3 integer representation.
#' @param index as an integer representation.
#' @export
h3_int_to_string <- function(index) {
    .Call('_placekey_h3_int_to_string', PACKAGE = 'placekey', index)
}

